---
- name: setup minecraft server
  hosts: minecraft
  remote_user: ubuntu
  become: yes  # Necessary for privileges to install packages

  tasks:
    - name: install packages
      ansible.builtin.command: add-apt-repository -y ppa:openjdk-r/ppa
        - apt update
        - apt install -y openjdk-21-jre-headless
        - ufw allow 25565
    - name: install server
      ansible.builtin.command:
        - mkdir /opt/minecraft
        - cd /opt/minecraft
        - wget https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar
        - java -Xms1024M -Xmx1024M -jar server.jar nogui
        - sleep 40
        - sed -i 's/false/true/p' eula.txt
        - java -Xms1024M -Xmx1024M -jar server.jar nogui
# https://aws.amazon.com/blogs/gametech/setting-up-a-minecraft-java-server-on-amazon-ec2/
    - name: setup start scripts
      command: 
        - touch start
        - printf '#!/bin/bash\njava -Xmx1300M -Xms1300M -jar server.jar nogui\n' >> start
        - chmod +x start
        - sleep 1
        - touch stop
        - printf '#!/bin/bash\nkill -9 $(ps -ef | pgrep -f "java")' >> stop
        - chmod +x stop
        - sleep 1
    - name: autostart
      command:
        - cd /etc/systemd/system/
        - touch minecraft.service
        - printf '[Unit]\nDescription=Minecraft Server on start up\nWants=network-online.target\n[Service]\nUser=minecraft\nWorkingDirectory=/opt/minecraft/server\nExecStart=/opt/minecraft/server/start\nStandardInput=null\n[Install]\nWantedBy=multi-user.target' >> minecraft.service
        - systemctl daemon-reload
        - systemctl enable minecraft.service
        - systemctl start minecraft.service
