---
- name: Setup Minecraft server
  hosts: minecraft
  remote_user: ubuntu
  become: yes  # Necessary for privileges to install packages

  tasks:
    - name: Add OpenJDK PPA repository and update apt cache
      ansible.builtin.shell: |
        add-apt-repository -y ppa:openjdk-r/ppa
        apt update

    - name: Install OpenJDK 21 JRE headless
      ansible.builtin.shell: apt install -y openjdk-21-jre-headless

    - name: Allow port 25565 through UFW
      ansible.builtin.shell: ufw allow 25565

    - name: Set up Minecraft server directory and download server jar
      ansible.builtin.shell: |
        mkdir -p /opt/minecraft
        cd /opt/minecraft
        wget https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar
    
    - name: Change ownership of /opt/minecraft/ to minecraft user and group
      ansible.builtin.shell: chown -R ubuntu:ubuntu /opt/minecraft

    - name: Accept EULA
      ansible.builtin.shell: echo 'eula=true' > /opt/minecraft/eula.txt

    - name: Create start script
      ansible.builtin.copy:
        dest: /opt/minecraft/start
        content: |
          #!/bin/bash
          java -Xmx1300M -Xms1300M -jar /opt/minecraft/server.jar nogui
        mode: '0755'

    - name: Create stop script
      ansible.builtin.copy:
        dest: /opt/minecraft/stop
        content: |
          #!/bin/bash
          kill -9 $(pgrep -f "java")
        mode: '0755'

    - name: Create systemd service file for Minecraft
      ansible.builtin.copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server on start up
          Wants=network-online.target

          [Service]
          User=ubuntu
          WorkingDirectory=/opt/minecraft
          ExecStart=/opt/minecraft/start
          ExecStop=/opt/minecraft/stop
          StandardInput=null

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.shell: systemctl daemon-reload

    - name: Enable Minecraft service
      ansible.builtin.shell: systemctl enable minecraft.service

    - name: Start Minecraft service
      ansible.builtin.shell: systemctl start minecraft.service
